# configuration for https://travis-ci.org/bitcoinj/bitcoinj
sudo: false
dist: trusty
language: java
addons:
  hosts:
    - host
  hostname: host
jdk: openjdk7
install:
# before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y protobuf-compiler
script:
  - gradle -q clean install
  - jdk_switcher use openjdk7
  - cd core
  - gradle -q clean build

